# 1.	Numpy Random Package:

The definition of a random number is not supposed to be a distinct number every time, but it means that the random number cannot be predicted logically.
The random is a module which is exists in the python numpy library. Random package contains the methods which is usually used for the generation of random numbers. Also, this package contains other some random data generation functions, and permutation and distribution functions.
The package is divided into three main types of methods which are:
1.	Simple random data
2.	Permutations 
3.	Distributions


## Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## 2a.  Simple Data Distribution:

Simple data distribution is used to draw random data or choice from a predefined dataset. Simple random data is draw using different methods of numpy random package which are used in different types of requirements of the program are as follows:

1.	“integer”, which returns random integers.
2.	“random”, which returns random floats.
3.	“choice”, which returns sample from a given data e.g. array.
4.	“bytes”, which returns random bytes.


In [2]:
# Generators.integers()
# Return random integers from low (inclusive) to high (exclusive).
array = np.random.randint(2, size=10)
print(array)

array2 = np.random.random_integers(low=2, high=10, size=10)
print(array2)

[0 0 1 1 1 0 0 1 1 1]
[ 2  6  7 10  6  8  2  9  7  9]


In [3]:
# Return random floats in the half-open interval [0.0, 1.0).

rand = np.random.random()
print(rand)

0.26936479252705303


In [4]:
# Generator.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)¶
# Generates a random sample from a given 1-D array 
rand_choice = np.random.choice(10, 3)
print(rand_choice)

# randomly choice from given array
rand_choice = np.random.choice([10,9,8,7,6], 4)
print(rand_choice)

[1 7 5]
[6 9 8 6]


In [5]:
# Generator.bytes(length)
# Return random bytes.

rand_byte = np.random.bytes(4)
print(rand_byte)

b'\xc7}J\x04'
