# 1.	Numpy Random Package:

The definition of a random number is not supposed to be a distinct number every time, but it means that the random number cannot be predicted logically.
The random is a module which is exists in the python numpy library. Random package contains the methods which is usually used for the generation of random numbers. Also, this package contains other some random data generation functions, and permutation and distribution functions.
The package is divided into three main types of methods which are:
1.	Simple random data
2.	Permutations 
3.	Distributions


## Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## 2a.  Simple Data Distribution:

Simple data distribution is used to draw random data or choice from a predefined dataset. Simple random data is draw using different methods of numpy random package which are used in different types of requirements of the program are as follows:

1.	“integer”, which returns random integers.
2.	“random”, which returns random floats.
3.	“choice”, which returns sample from a given data e.g. array.
4.	“bytes”, which returns random bytes.


In [2]:
# Generators.integers()
# Return random integers from low (inclusive) to high (exclusive).
array = np.random.randint(2, size=10)
print(array)

array2 = np.random.random_integers(low=2, high=10, size=10)
print(array2)

[0 0 1 1 1 0 0 1 1 1]
[ 2  6  7 10  6  8  2  9  7  9]


In [3]:
# Return random floats in the half-open interval [0.0, 1.0).

rand = np.random.random()
print(rand)

0.26936479252705303


In [4]:
# Generator.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)¶
# Generates a random sample from a given 1-D array 
rand_choice = np.random.choice(10, 3)
print(rand_choice)

# randomly choice from given array
rand_choice = np.random.choice([10,9,8,7,6], 4)
print(rand_choice)

[1 7 5]
[6 9 8 6]


In [5]:
# Generator.bytes(length)
# Return random bytes.

rand_byte = np.random.bytes(4)
print(rand_byte)

b'\xc7}J\x04'


## 2b.	Permutations:

Permutations is defined as an arrangement of members of a set. We use permutation to shuffle or permute the sequence of data. In numpy random package there are two types of permutation functions are:
1.	“shuffle”, which modifies am array in place by shuffling its members.
2.	“permutation”, which randomly permutes an array or also can return a permuted array.


In [6]:
# Generator.shuffle(x, axis=0)
# Modify a sequence in-place by shuffling its contents.
# The order of arrays is changed but their contents remains the same.

array = np.arange(10)
print(array)
np.random.shuffle(array)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 8 6 7 9 1 2 5 3 4]


In [7]:
# Generator.permutation(x, axis=0)
# Randomly permute a sequence, or return a permuted range.

array = np.random.permutation(6)  
print(array)  

arr = [ 0, 11,  2,  6,  8,  3,  7,  5,  9,  4, 10,  1]
arr = np.random.permutation(arr)  
print(arr)  

[4 5 0 3 2 1]
[ 8  9  1  3  6  0  5  7 11  4 10  2]
